@extends('errors.layout')
@section('title', 'Akses ditolak')
@section('code', '403')
@section('heading', 'Akses ditolak')
@section('message', 'Akun Anda tidak memiliki izin untuk membuka atau mengubah sumber daya ini.')
