@extends('errors.layout')
@section('title', 'Halaman tidak ditemukan')
@section('code', '404')
@section('heading', 'Halaman tidak ditemukan')
@section('message', 'Alamat yang Anda buka tidak tersedia atau sudah dipindahkan.')
