@extends('errors.layout')
@section('title', 'Terlalu banyak permintaan')
@section('code', '429')
@section('heading', 'Terlalu banyak permintaan')
@section('message', 'Tunggu sebentar sebelum mencoba kembali agar sistem tetap dapat digunakan.')
